services:
  tv_app:
    build:
      context: .
      dockerfile: prod.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${UID:-1000}
        - USER=tv
        - GROUP=tv
    container_name: tv-calendar-app
    networks:
      - tv-internal-network
    restart: always
    working_dir: /var/www/
    ports:
      - '9001'
    volumes:
      - ./docker/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - tv-calendar-sessions:/tmp

  tv_nginx:
    image: nginx:1.19-alpine
    container_name: tv-calendar-nginx
    networks:
      - proxy
      - tv-internal-network
    restart: always
    environment:
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - '9999:80'
    #   - '443:443'
    volumes:
      - .:/var/www
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/allow-cloudflare-only.conf:/etc/nginx/allow-cloudflare-only.conf
      - ./docker/nginx/set-real-ips.conf:/etc/nginx/set-real-ips.conf

  tv_db:
    container_name: tv-calendar-db
    networks:
      - tv-internal-network
    image: postgres:17-bookworm
    volumes:
      - ./storage:/storage
      - tv-calendar-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432

  tv_adminer:
    image: adminer
    networks:
      - tv-internal-network
    restart: always
    ports:
      - 8001:8080

  tv_cron:
    build: ./docker/cron
    networks:
      - tv-internal-network
    restart: always
    volumes:
      - .:/var/www
      - ./docker/cron/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db

volumes:
  tv-calendar-db-data:
  tv-calendar-sessions:

networks:
  proxy:
    name: proxy
    external: true
  internal-network:
    name: tv-internal-network
    external: false
