#!/usr/bin/bash

if [ "$1" == "app" ]; then
app = docker exec -t tv-calendar-app bash -c
    
    if [ "$2" == "doctrine" ]; then
    eval $app "./bin/doctrine $3"
    fi 
    if [ "$2" == "composer" ]; then
    shift
    shift
    eval $app "composer $@"
    fi 
    if [ "$2" == "test" ]; then
    shift
    shift
    eval $app "./vendor/bin/phpunit $@"
    fi
fi

if [ "$1" == "npm" ]; then 
    docker compose run --rm node $@
fi