<?php

declare(strict_types=1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241211123247 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE episodes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tv_maze_episode_id INT NOT NULL, name TEXT NOT NULL, season SMALLINT DEFAULT NULL, number SMALLINT DEFAULT NULL, summary TEXT DEFAULT NULL, airstamp TIMESTAMP(0) WITH TIME ZONE NOT NULL, type VARCHAR(255) DEFAULT NULL, runtime SMALLINT DEFAULT NULL, image_medium TEXT DEFAULT NULL, image_original TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shows_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7DD55EDDAD7ED998 ON episodes (shows_id)');
        $this->addSql('CREATE TABLE shows (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tv_maze_id INT NOT NULL, imdb_id VARCHAR(255) NOT NULL, name TEXT NOT NULL, summary TEXT DEFAULT NULL, genres TEXT NOT NULL, status VARCHAR(255) NOT NULL, runtime SMALLINT DEFAULT NULL, premiered VARCHAR(255) DEFAULT NULL, ended VARCHAR(255) DEFAULT NULL, official_site TEXT DEFAULT NULL, weight SMALLINT DEFAULT 0 NOT NULL, network_name VARCHAR(255) DEFAULT NULL, network_country VARCHAR(255) DEFAULT NULL, web_channel_name VARCHAR(255) DEFAULT NULL, image_medium TEXT DEFAULT NULL, image_original TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE episodes ADD CONSTRAINT FK_7DD55EDDAD7ED998 FOREIGN KEY (shows_id) REFERENCES shows (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE episodes DROP CONSTRAINT FK_7DD55EDDAD7ED998');
        $this->addSql('DROP TABLE episodes');
        $this->addSql('DROP TABLE shows');
    }
}
